### ISSUE TITLE
SyntaxError: 'import' and 'export'

### ISSUE THREAD

**Issue by edgehero** [ro31337/gulp-react-easy#1]
I'm getting this error:

events.js:154
      throw er; // Unhandled 'error' event
      ^
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

How to see the debug? and what could be the cause?

**Comment by ro31337** [comment]
Is it a new project? Hard to say what it is, mind publishing the code to github and post full error message?

**Comment by edgehero** [comment]
Yes it was, but i solved it already.
i used the wrong import for a file. 
this one made it work for me: import App from './components/app.jsx';

Its pretty cool what you did in this project, you saved hours of headache for me.

**Comment by ro31337** [comment]
@edgehero thanks, I closed this issue. I appreciate if you can tell a friend about this gulp plugin or share about your experience in a blog when you have time. Thanks!
